### ISSUE TITLE
badge-xxx css location?

### ISSUE THREAD

**Issue by Aberdeener** [highcastle007/MONARCH#1]
Hello, playing around with this for fun, and I am trying to change the colours of player badges. When I use inspect element it says it is getting the background-color from monarch.css, so I went and changed the .badge-danger background color in the file and reuploaded, but it doesnt change when I refresh my page. Where are badge background-colors defined in this theme? I have changed them previously with the default theme.

**Comment by agenthighcastle** [comment]
Hi,
I only edited .badge-danger which is in monarch.css, every other badge is currently dependant on **bootstrap.min.css**

I would recommend adding every badge to **custom.css** since this won't be overwritten with the next update.

**Comment by Aberdeener** [comment]
Hi, thanks!
I have done that but when I set my groups to use that badge, they do not
use it and it has no colour.

**Comment by highcastle007** [comment]
Could you post your code

**Comment by highcastle007** [comment]
Nvm, I found the issue. Will be fixed with the next update

**Comment by Aberdeener** [comment]
Thanks! Closed.
