### ISSUE TITLE
Broken buttons throughout

### ISSUE THREAD

**Issue by Aberdeener** [highcastle007/MONARCH#3]
Hello, sorry for all the trouble recently xD

I would like to report that the Post Moderation & Share buttons do nothing, along with the Spam, Delete and Report buttons when I view a topic. When I create a topic, the Cancel button does not work either. On a profile, the buttons under a profile post Reply and Edit do not work either.

I will update this if I find more

UPDATE: When I make custom pages and assign them to be under the "more dropdown", the dropdown does nothing when I click on it.
UPDATE 2: The About and Forum buttons when viewing a users profile are also non-functional

**Comment by highcastle007** [comment]
Has been resolved.
